### ISSUE TITLE
Błąd pobierania w CoreELEC

### ISSUE THREAD

**Issue by kodiwpigulce** [tbrek/tbrek-kodi-repo#2]
Cześć, fajny pomysł na wtyczkę ale w CoreELEC na boxie nie działa. Po wybraniu materiału do pobrania nic się nie dzieję. W logach jest tylko to: 

`2021-01-10 21:15:24.710 T:3340759936  NOTICE: [xbmcswift2] Request for "/record_epg/Polsat News HD/Pogoda /2021-01-10 22:40:00/2021-01-10 22:55:00" matches rule for function "record_epg"
2021-01-10 21:15:24.738 T:3077522304   ERROR: u'No channel Polsat News HD 4'`

**Comment by tbrek** [comment]
Pokaz fragment m3u, bo z tego co widac w logu nazwa kanalu jest zla.

**Comment by kodiwpigulce** [comment]
To lista z telelevidenie plus nasze epg i dzieje się to z każdym kanałem i programem. Sprawdziłem kilka programów i do każdego dodana jest cyfra "4". 

#EXTINF:0 id="3_535" group-title="Informacje" timeshift="3" tvg-id="PolsatNews.pl" tvg-name="Polsat News HD" tvg-logo="http://my.trelelelelelleee.com/assets/logo/4264.png",Polsat News HD

**Comment by tbrek** [comment]
Lista tele oryginalna bez modyfikacji?

**Comment by kodiwpigulce** [comment]
bez modyfikacji, a na win10 tworzy się  plik o rozmiarze 0

**Comment by tbrek** [comment]
> bez modyfikacji, a na win10 tworzy się  plik o rozmiarze 0 

Ok. Sprawdzę, bo używam m3u po lekkim tuningu.

**Comment by tbrek** [comment]
@kodiwpigulce m3u czytasz z IPTV Simple Client czy url?

**Comment by kodiwpigulce** [comment]
z IPTV Simple Client i wybieram z przewodnika z menu kontekstowego Download from Archive

**Comment by kodiwpigulce** [comment]
Ok, dodałem jeszcze URL playlisty do wtyczki i teraz wygląda na to, że działa. :)

**Comment by tbrek** [comment]
> Ok, dodałem jeszcze URL playlisty do wtyczki i teraz wygląda na to, że działa. :) 

Super. W każdym bądź razie, u mnie działa z URL i z Listą Z Simple IPTV.

Niestety nie mam CoreELEC, żeby sprawdzić. Dodam do README dopisek do konfiguracji.

**Comment by kodiwpigulce** [comment]
Dzięki, zamykamy.

**Comment by kodiwpigulce** [comment]
Nie będę nowego issue otwierał ale mógłbyś sprawdzić jeśli masz możliwość czy działa u Ciebie to na androidzie? Bo nie u mnie tworzy plik o wadze 0, dostaje w sekundę komunikat, że audycja pobrana. Jednak plik waży 0. W logach nic nie widać.

**Comment by tbrek** [comment]
> Nie będę nowego issue otwierał ale mógłbyś sprawdzić jeśli masz możliwość czy działa u Ciebie to na androidzie? Bo nie u mnie tworzy plik o wadze 0, dostaje w sekundę komunikat, że audycja pobrana. Jednak plik waży 0. W logach nic nie widać.

Zainstalowałem na emulatorze i mam to samo. Podejrzewam jakiś problem z `ffmpeg`.
