### ISSUE TITLE
What's the functionnality ?

### ISSUE THREAD

**Issue by electro575** [tbrek/tbrek-kodi-repo#23]
Hi,

I have installed the latest versiàon for Kodi 20.2.

I have configure the ffmpeg path, the m3u path.

What can be the register path ?

Your add-on offer register program or see m3u file with capability to return back in time ?

Thanks a lot for your explanation.

**Comment by tbrek** [comment]
Can you elaborate on 

> What can be the register path ?

I'm not sure what you mean.

**Comment by electro575** [comment]
The path for register film from m3u channel TV

**Comment by tbrek** [comment]
> The path for register film from m3u channel TV

<img width="1016" alt="SCR-20240127-pqym" src="https://github.com/tbrek/tbrek-kodi-repo/assets/9820995/6ea51c25-4ba6-43ab-83ff-63cc01b15766">
