### ISSUE TITLE
Polskie tłumaczenie?

### ISSUE THREAD

**Issue by notoco** [tbrek/tbrek-kodi-repo#3]
"A niechaj narodowie wżdy postronni znają, iż Polacy nie gęsi, iż swój język mają. ..."
Wtyczka niesamowita, działa świetnie. 
Zacząłem się brać za tłumaczenie na PL, ale widzę że tu krajan :)
Jest szansa na polską wersję?

**Comment by tbrek** [comment]
Oczywiście.

**Comment by notoco** [comment]
Rewelacja... naprawdę rewelacja...
W końcu szansa na obejrzenie niszowych dokumentów filmów  nie tylko 3 dni wstecz, ale też w dowolnej chwili.

**Comment by tbrek** [comment]
Wersja 0.3.0 posiada polskie tłumaczenie. Aktualizacja powinna być już w repo.

**Comment by notoco** [comment]
Jest i działa...
